spring:
  application:
    name: maids

# ====================================
# - Database Configuration
# ====================================
  jpa:
    properties:
      hibernate:
        format-sql: false
    show-sql: true
